// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

class NativeLibrary {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeLibrary(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeLibrary.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  ffi.Pointer<ffi.Char> getHostname() {
    return _getHostname();
  }

  late final _getHostnamePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'getHostname');
  late final _getHostname =
      _getHostnamePtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> getPlatform() {
    return _getPlatform();
  }

  late final _getPlatformPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'getPlatform');
  late final _getPlatform =
      _getPlatformPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> getDistribution() {
    return _getDistribution();
  }

  late final _getDistributionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'getDistribution');
  late final _getDistribution =
      _getDistributionPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> getKernelRelease() {
    return _getKernelRelease();
  }

  late final _getKernelReleasePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'getKernelRelease');
  late final _getKernelRelease =
      _getKernelReleasePtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> getCPUModel() {
    return _getCPUModel();
  }

  late final _getCPUModelPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'getCPUModel');
  late final _getCPUModel =
      _getCPUModelPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> getCPUCoreCount() {
    return _getCPUCoreCount();
  }

  late final _getCPUCoreCountPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'getCPUCoreCount');
  late final _getCPUCoreCount =
      _getCPUCoreCountPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> getCPUSpeed() {
    return _getCPUSpeed();
  }

  late final _getCPUSpeedPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'getCPUSpeed');
  late final _getCPUSpeed =
      _getCPUSpeedPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();
}

final class __mbstate_t extends ffi.Struct {
  @ffi.Int()
  external int __count;

  external UnnamedUnion1 __value;
}

final class UnnamedUnion1 extends ffi.Union {
  @ffi.UnsignedInt()
  external int __wch;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Char> __wchb;
}

final class _IO_FILE extends ffi.Struct {
  @ffi.Int()
  external int _flags;

  external ffi.Pointer<ffi.Char> _IO_read_ptr;

  external ffi.Pointer<ffi.Char> _IO_read_end;

  external ffi.Pointer<ffi.Char> _IO_read_base;

  external ffi.Pointer<ffi.Char> _IO_write_base;

  external ffi.Pointer<ffi.Char> _IO_write_ptr;

  external ffi.Pointer<ffi.Char> _IO_write_end;

  external ffi.Pointer<ffi.Char> _IO_buf_base;

  external ffi.Pointer<ffi.Char> _IO_buf_end;

  external ffi.Pointer<ffi.Char> _IO_save_base;

  external ffi.Pointer<ffi.Char> _IO_backup_base;

  external ffi.Pointer<ffi.Char> _IO_save_end;

  external ffi.Pointer<_IO_marker> _markers;

  external ffi.Pointer<_IO_FILE> _chain;

  @ffi.Int()
  external int _fileno;

  @ffi.Int()
  external int _flags2;

  @__off_t()
  external int _old_offset;

  @ffi.UnsignedShort()
  external int _cur_column;

  @ffi.SignedChar()
  external int _vtable_offset;

  @ffi.Array.multi([1])
  external ffi.Array<ffi.Char> _shortbuf;

  external ffi.Pointer<_IO_lock_t> _lock;

  @__off64_t()
  external int _offset;

  external ffi.Pointer<_IO_codecvt> _codecvt;

  external ffi.Pointer<_IO_wide_data> _wide_data;

  external ffi.Pointer<_IO_FILE> _freeres_list;

  external ffi.Pointer<ffi.Void> _freeres_buf;

  @ffi.Size()
  external int __pad5;

  @ffi.Int()
  external int _mode;

  @ffi.Array.multi([20])
  external ffi.Array<ffi.Char> _unused2;
}

final class _IO_marker extends ffi.Opaque {}

typedef __off_t = ffi.Long;
typedef Dart__off_t = int;
typedef _IO_lock_t = ffi.Void;
typedef Dart_IO_lock_t = void;
typedef __off64_t = ffi.Long;
typedef Dart__off64_t = int;

final class _IO_codecvt extends ffi.Opaque {}

final class _IO_wide_data extends ffi.Opaque {}

final class __locale_struct extends ffi.Struct {
  @ffi.Array.multi([13])
  external ffi.Array<ffi.Pointer<__locale_data>> __locales;

  external ffi.Pointer<ffi.UnsignedShort> __ctype_b;

  external ffi.Pointer<ffi.Int> __ctype_tolower;

  external ffi.Pointer<ffi.Int> __ctype_toupper;

  @ffi.Array.multi([13])
  external ffi.Array<ffi.Pointer<ffi.Char>> __names;
}

final class __locale_data extends ffi.Opaque {}

final class max_align_t extends ffi.Opaque {}

final class __fsid_t extends ffi.Struct {
  @ffi.Array.multi([2])
  external ffi.Array<ffi.Int> __val;
}

final class timespec extends ffi.Struct {
  @__time_t()
  external int tv_sec;

  @__syscall_slong_t()
  external int tv_nsec;
}

typedef __time_t = ffi.Long;
typedef Dart__time_t = int;
typedef __syscall_slong_t = ffi.Long;
typedef Dart__syscall_slong_t = int;

final class sched_param extends ffi.Struct {
  @ffi.Int()
  external int sched_priority;
}

final class cpu_set_t extends ffi.Struct {
  @ffi.Array.multi([16])
  external ffi.Array<__cpu_mask> __bits;
}

typedef __cpu_mask = ffi.UnsignedLong;
typedef Dart__cpu_mask = int;

final class timeval extends ffi.Struct {
  @__time_t()
  external int tv_sec;

  @__suseconds_t()
  external int tv_usec;
}

typedef __suseconds_t = ffi.Long;
typedef Dart__suseconds_t = int;

final class timex extends ffi.Opaque {}

final class tm extends ffi.Struct {
  @ffi.Int()
  external int tm_sec;

  @ffi.Int()
  external int tm_min;

  @ffi.Int()
  external int tm_hour;

  @ffi.Int()
  external int tm_mday;

  @ffi.Int()
  external int tm_mon;

  @ffi.Int()
  external int tm_year;

  @ffi.Int()
  external int tm_wday;

  @ffi.Int()
  external int tm_yday;

  @ffi.Int()
  external int tm_isdst;

  @ffi.Long()
  external int tm_gmtoff;

  external ffi.Pointer<ffi.Char> tm_zone;
}

final class itimerspec extends ffi.Struct {
  external timespec it_interval;

  external timespec it_value;
}

final class sigevent extends ffi.Opaque {}

final class __atomic_wide_counter extends ffi.Union {
  @ffi.UnsignedLongLong()
  external int __value64;

  external UnnamedStruct1 __value32;
}

final class UnnamedStruct1 extends ffi.Struct {
  @ffi.UnsignedInt()
  external int __low;

  @ffi.UnsignedInt()
  external int __high;
}

final class __pthread_internal_list extends ffi.Struct {
  external ffi.Pointer<__pthread_internal_list> __prev;

  external ffi.Pointer<__pthread_internal_list> __next;
}

final class __pthread_internal_slist extends ffi.Struct {
  external ffi.Pointer<__pthread_internal_slist> __next;
}

final class __pthread_mutex_s extends ffi.Struct {
  @ffi.Int()
  external int __lock;

  @ffi.UnsignedInt()
  external int __count;

  @ffi.Int()
  external int __owner;

  @ffi.UnsignedInt()
  external int __nusers;

  @ffi.Int()
  external int __kind;

  @ffi.Short()
  external int __spins;

  @ffi.Short()
  external int __elision;

  external __pthread_list_t __list;
}

typedef __pthread_list_t = __pthread_internal_list;

final class __pthread_rwlock_arch_t extends ffi.Struct {
  @ffi.UnsignedInt()
  external int __readers;

  @ffi.UnsignedInt()
  external int __writers;

  @ffi.UnsignedInt()
  external int __wrphase_futex;

  @ffi.UnsignedInt()
  external int __writers_futex;

  @ffi.UnsignedInt()
  external int __pad3;

  @ffi.UnsignedInt()
  external int __pad4;

  @ffi.Int()
  external int __cur_writer;

  @ffi.Int()
  external int __shared;

  @ffi.SignedChar()
  external int __rwelision;

  @ffi.Array.multi([7])
  external ffi.Array<ffi.UnsignedChar> __pad1;

  @ffi.UnsignedLong()
  external int __pad2;

  @ffi.UnsignedInt()
  external int __flags;
}

final class __pthread_cond_s extends ffi.Struct {
  external __atomic_wide_counter __wseq;

  external __atomic_wide_counter __g1_start;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.UnsignedInt> __g_refs;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.UnsignedInt> __g_size;

  @ffi.UnsignedInt()
  external int __g1_orig_size;

  @ffi.UnsignedInt()
  external int __wrefs;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.UnsignedInt> __g_signals;
}

final class __once_flag extends ffi.Struct {
  @ffi.Int()
  external int __data;
}

final class pthread_mutexattr_t extends ffi.Union {
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Char> __size;

  @ffi.Int()
  external int __align;
}

final class pthread_condattr_t extends ffi.Union {
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Char> __size;

  @ffi.Int()
  external int __align;
}

final class pthread_attr_t extends ffi.Union {
  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_mutex_t extends ffi.Union {
  external __pthread_mutex_s __data;

  @ffi.Array.multi([40])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_cond_t extends ffi.Union {
  external __pthread_cond_s __data;

  @ffi.Array.multi([48])
  external ffi.Array<ffi.Char> __size;

  @ffi.LongLong()
  external int __align;
}

final class pthread_rwlock_t extends ffi.Union {
  external __pthread_rwlock_arch_t __data;

  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_rwlockattr_t extends ffi.Union {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_barrier_t extends ffi.Union {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_barrierattr_t extends ffi.Union {
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Char> __size;

  @ffi.Int()
  external int __align;
}

final class __sigset_t extends ffi.Struct {
  @ffi.Array.multi([16])
  external ffi.Array<ffi.UnsignedLong> __val;
}

final class __jmp_buf_tag extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Long> __jmpbuf;

  @ffi.Int()
  external int __mask_was_saved;

  external __sigset_t __saved_mask;
}

final class _pthread_cleanup_buffer extends ffi.Struct {
  external ffi
      .Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>
      __routine;

  external ffi.Pointer<ffi.Void> __arg;

  @ffi.Int()
  external int __canceltype;

  external ffi.Pointer<_pthread_cleanup_buffer> __prev;
}

const int PTHREAD_CREATE_JOINABLE = 0;

const int PTHREAD_CREATE_DETACHED = 1;

const int PTHREAD_MUTEX_TIMED_NP = 0;

const int PTHREAD_MUTEX_RECURSIVE_NP = 1;

const int PTHREAD_MUTEX_ERRORCHECK_NP = 2;

const int PTHREAD_MUTEX_ADAPTIVE_NP = 3;

const int PTHREAD_MUTEX_NORMAL = 0;

const int PTHREAD_MUTEX_RECURSIVE = 1;

const int PTHREAD_MUTEX_ERRORCHECK = 2;

const int PTHREAD_MUTEX_DEFAULT = 0;

const int PTHREAD_MUTEX_FAST_NP = 0;

const int PTHREAD_MUTEX_STALLED = 0;

const int PTHREAD_MUTEX_STALLED_NP = 0;

const int PTHREAD_MUTEX_ROBUST = 1;

const int PTHREAD_MUTEX_ROBUST_NP = 1;

const int PTHREAD_PRIO_NONE = 0;

const int PTHREAD_PRIO_INHERIT = 1;

const int PTHREAD_PRIO_PROTECT = 2;

const int PTHREAD_RWLOCK_PREFER_READER_NP = 0;

const int PTHREAD_RWLOCK_PREFER_WRITER_NP = 1;

const int PTHREAD_RWLOCK_PREFER_WRITER_NONRECURSIVE_NP = 2;

const int PTHREAD_RWLOCK_DEFAULT_NP = 0;

const int PTHREAD_INHERIT_SCHED = 0;

const int PTHREAD_EXPLICIT_SCHED = 1;

const int PTHREAD_SCOPE_SYSTEM = 0;

const int PTHREAD_SCOPE_PROCESS = 1;

const int PTHREAD_PROCESS_PRIVATE = 0;

const int PTHREAD_PROCESS_SHARED = 1;

const int PTHREAD_CANCEL_ENABLE = 0;

const int PTHREAD_CANCEL_DISABLE = 1;

const int PTHREAD_CANCEL_DEFERRED = 0;

const int PTHREAD_CANCEL_ASYNCHRONOUS = 1;

const int __ISwupper = 0;

const int __ISwlower = 1;

const int __ISwalpha = 2;

const int __ISwdigit = 3;

const int __ISwxdigit = 4;

const int __ISwspace = 5;

const int __ISwprint = 6;

const int __ISwgraph = 7;

const int __ISwblank = 8;

const int __ISwcntrl = 9;

const int __ISwpunct = 10;

const int __ISwalnum = 11;

const int _ISwupper = 16777216;

const int _ISwlower = 33554432;

const int _ISwalpha = 67108864;

const int _ISwdigit = 134217728;

const int _ISwxdigit = 268435456;

const int _ISwspace = 536870912;

const int _ISwprint = 1073741824;

const int _ISwgraph = -2147483648;

const int _ISwblank = 65536;

const int _ISwcntrl = 131072;

const int _ISwpunct = 262144;

const int _ISwalnum = 524288;

const int _GLIBCXX_IOSTREAM = 1;

const int _REQUIRES_FREESTANDING_H = 1;

const int _GLIBCXX_CXX_CONFIG_H = 1;

const int _GLIBCXX_RELEASE = 13;

const int __GLIBCXX__ = 20230913;

const int _GLIBCXX_HAVE_ATTRIBUTE_VISIBILITY = 1;

const int _GLIBCXX_USE_DEPRECATED = 1;

const int _GLIBCXX_NOEXCEPT_QUAL = 1;

const int _GLIBCXX_EXTERN_TEMPLATE = 1;

const int _GLIBCXX_USE_DUAL_ABI = 1;

const int _GLIBCXX_USE_CXX11_ABI = 1;

const int _GLIBCXX_INLINE_VERSION = 0;

const int _GLIBCXX_HAVE_IS_CONSTANT_EVALUATED = 1;

const int _GLIBCXX_VERBOSE_ASSERT = 1;

const int _GLIBCXX_USE_ALLOCATOR_NEW = 1;

const int _GLIBCXX_OS_DEFINES = 1;

const int __NO_CTYPE = 1;

const int _FEATURES_H = 1;

const int _ISOC95_SOURCE = 1;

const int _ISOC99_SOURCE = 1;

const int _ISOC11_SOURCE = 1;

const int _ISOC2X_SOURCE = 1;

const int _POSIX_SOURCE = 1;

const int _POSIX_C_SOURCE = 200809;

const int _XOPEN_SOURCE = 700;

const int _XOPEN_SOURCE_EXTENDED = 1;

const int _LARGEFILE64_SOURCE = 1;

const int _DEFAULT_SOURCE = 1;

const int _ATFILE_SOURCE = 1;

const int _DYNAMIC_STACK_SIZE_SOURCE = 1;

const int __GLIBC_USE_ISOC2X = 1;

const int __USE_ISOC11 = 1;

const int __USE_ISOC99 = 1;

const int __USE_ISOC95 = 1;

const int __USE_ISOCXX11 = 1;

const int __USE_POSIX = 1;

const int __USE_POSIX2 = 1;

const int __USE_POSIX199309 = 1;

const int __USE_POSIX199506 = 1;

const int __USE_XOPEN2K = 1;

const int __USE_XOPEN2K8 = 1;

const int __USE_XOPEN = 1;

const int __USE_XOPEN_EXTENDED = 1;

const int __USE_UNIX98 = 1;

const int _LARGEFILE_SOURCE = 1;

const int __USE_XOPEN2K8XSI = 1;

const int __USE_XOPEN2KXSI = 1;

const int __USE_LARGEFILE = 1;

const int __USE_LARGEFILE64 = 1;

const int __WORDSIZE = 64;

const int __WORDSIZE_TIME64_COMPAT32 = 1;

const int __SYSCALL_WORDSIZE = 64;

const int __TIMESIZE = 64;

const int __USE_MISC = 1;

const int __USE_ATFILE = 1;

const int __USE_DYNAMIC_STACK_SIZE = 1;

const int __USE_GNU = 1;

const int __USE_FORTIFY_LEVEL = 0;

const int __GLIBC_USE_DEPRECATED_GETS = 0;

const int __GLIBC_USE_DEPRECATED_SCANF = 0;

const int __GLIBC_USE_C2X_STRTOL = 1;

const int _STDC_PREDEF_H = 1;

const int __STDC_IEC_559__ = 1;

const int __STDC_IEC_60559_BFP__ = 201404;

const int __STDC_IEC_559_COMPLEX__ = 1;

const int __STDC_IEC_60559_COMPLEX__ = 201404;

const int __STDC_ISO_10646__ = 201706;

const int __GNU_LIBRARY__ = 6;

const int __GLIBC__ = 2;

const int __GLIBC_MINOR__ = 38;

const int _SYS_CDEFS_H = 1;

const int __THROW = 1;

const int __THROWNL = 1;

const int __glibc_c99_flexarr_available = 1;

const int __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI = 0;

const int __HAVE_GENERIC_SELECTION = 0;

const int _GLIBCXX_NO_OBSOLETE_ISINF_ISNAN_DYNAMIC = 1;

const int _GLIBCXX_HAVE_FLOAT128_MATH = 1;

const int _GLIBCXX_GTHREAD_USE_WEAK = 0;

const int _GLIBCXX_CPU_DEFINES = 1;

const int _GLIBCXX_USE_WEAK_REF = 1;

const int _GLIBCXX_USE_STD_SPEC_FUNCS = 1;

const int _GLIBCXX_FAST_MATH = 0;

const int _GLIBCXX_USE_C99_MATH = 1;

const int _GLIBCXX_USE_C99_COMPLEX = 1;

const int _GLIBCXX_USE_C99_STDIO = 1;

const int _GLIBCXX_USE_C99_STDLIB = 1;

const int _GLIBCXX_USE_C99_WCHAR = 1;

const int _GLIBCXX_USE_FLOAT128 = 1;

const int _GLIBCXX_FLOAT_IS_IEEE_BINARY32 = 1;

const int _GLIBCXX_DOUBLE_IS_IEEE_BINARY64 = 1;

const int _GLIBCXX_HAVE_BUILTIN_HAS_UNIQ_OBJ_REP = 1;

const int _GLIBCXX_HAVE_BUILTIN_IS_AGGREGATE = 1;

const int _GLIBCXX_HAVE_BUILTIN_IS_SAME = 1;

const int _GLIBCXX_HAVE_BUILTIN_LAUNDER = 1;

const int _PSTL_VERSION = 12000;

const int _PSTL_VERSION_MAJOR = 12;

const int _PSTL_VERSION_MINOR = 0;

const int _PSTL_VERSION_PATCH = 0;

const int _PSTL_USAGE_WARNINGS = 0;

const int _PSTL_GCC_VERSION = 40201;

const int _PSTL_CLANG_VERSION = 160006;

const int _PSTL_UDR_PRESENT = 0;

const String _PSTL_PRAGMA_LOCATION = ' [Parallel STL message]: ';

const int _GLIBCXX_HAVE_ACOSF = 1;

const int _GLIBCXX_HAVE_ACOSL = 1;

const int _GLIBCXX_HAVE_ALIGNED_ALLOC = 1;

const int _GLIBCXX_HAVE_ARC4RANDOM = 1;

const int _GLIBCXX_HAVE_ARPA_INET_H = 1;

const int _GLIBCXX_HAVE_ASINF = 1;

const int _GLIBCXX_HAVE_ASINL = 1;

const int _GLIBCXX_HAVE_AS_SYMVER_DIRECTIVE = 1;

const int _GLIBCXX_HAVE_ATAN2F = 1;

const int _GLIBCXX_HAVE_ATAN2L = 1;

const int _GLIBCXX_HAVE_ATANF = 1;

const int _GLIBCXX_HAVE_ATANL = 1;

const int _GLIBCXX_HAVE_ATOMIC_LOCK_POLICY = 1;

const int _GLIBCXX_HAVE_AT_QUICK_EXIT = 1;

const int _GLIBCXX_HAVE_CEILF = 1;

const int _GLIBCXX_HAVE_CEILL = 1;

const int _GLIBCXX_HAVE_COMPLEX_H = 1;

const int _GLIBCXX_HAVE_COSF = 1;

const int _GLIBCXX_HAVE_COSHF = 1;

const int _GLIBCXX_HAVE_COSHL = 1;

const int _GLIBCXX_HAVE_COSL = 1;

const int _GLIBCXX_HAVE_DECL_STRNLEN = 1;

const int _GLIBCXX_HAVE_DIRENT_H = 1;

const int _GLIBCXX_HAVE_DIRFD = 1;

const int _GLIBCXX_HAVE_DLFCN_H = 1;

const int _GLIBCXX_HAVE_ENDIAN_H = 1;

const int _GLIBCXX_HAVE_EXCEPTION_PTR_SINCE_GCC46 = 1;

const int _GLIBCXX_HAVE_EXECINFO_H = 1;

const int _GLIBCXX_HAVE_EXPF = 1;

const int _GLIBCXX_HAVE_EXPL = 1;

const int _GLIBCXX_HAVE_FABSF = 1;

const int _GLIBCXX_HAVE_FABSL = 1;

const int _GLIBCXX_HAVE_FCNTL_H = 1;

const int _GLIBCXX_HAVE_FDOPENDIR = 1;

const int _GLIBCXX_HAVE_FENV_H = 1;

const int _GLIBCXX_HAVE_FINITE = 1;

const int _GLIBCXX_HAVE_FINITEF = 1;

const int _GLIBCXX_HAVE_FINITEL = 1;

const int _GLIBCXX_HAVE_FLOAT_H = 1;

const int _GLIBCXX_HAVE_FLOORF = 1;

const int _GLIBCXX_HAVE_FLOORL = 1;

const int _GLIBCXX_HAVE_FMODF = 1;

const int _GLIBCXX_HAVE_FMODL = 1;

const int _GLIBCXX_HAVE_FREXPF = 1;

const int _GLIBCXX_HAVE_FREXPL = 1;

const int _GLIBCXX_HAVE_GETENTROPY = 1;

const int _GLIBCXX_HAVE_GETIPINFO = 1;

const int _GLIBCXX_HAVE_GETS = 1;

const int _GLIBCXX_HAVE_HYPOT = 1;

const int _GLIBCXX_HAVE_HYPOTF = 1;

const int _GLIBCXX_HAVE_HYPOTL = 1;

const int _GLIBCXX_HAVE_ICONV = 1;

const int _GLIBCXX_HAVE_INTTYPES_H = 1;

const int _GLIBCXX_HAVE_ISINFF = 1;

const int _GLIBCXX_HAVE_ISINFL = 1;

const int _GLIBCXX_HAVE_ISNANF = 1;

const int _GLIBCXX_HAVE_ISNANL = 1;

const int _GLIBCXX_HAVE_ISWBLANK = 1;

const int _GLIBCXX_HAVE_LC_MESSAGES = 1;

const int _GLIBCXX_HAVE_LDEXPF = 1;

const int _GLIBCXX_HAVE_LDEXPL = 1;

const int _GLIBCXX_HAVE_LIBINTL_H = 1;

const int _GLIBCXX_HAVE_LIMIT_AS = 1;

const int _GLIBCXX_HAVE_LIMIT_DATA = 1;

const int _GLIBCXX_HAVE_LIMIT_FSIZE = 1;

const int _GLIBCXX_HAVE_LIMIT_RSS = 1;

const int _GLIBCXX_HAVE_LIMIT_VMEM = 0;

const int _GLIBCXX_HAVE_LINK = 1;

const int _GLIBCXX_HAVE_LINK_H = 1;

const int _GLIBCXX_HAVE_LINUX_FUTEX = 1;

const int _GLIBCXX_HAVE_LINUX_RANDOM_H = 1;

const int _GLIBCXX_HAVE_LINUX_TYPES_H = 1;

const int _GLIBCXX_HAVE_LOCALE_H = 1;

const int _GLIBCXX_HAVE_LOG10F = 1;

const int _GLIBCXX_HAVE_LOG10L = 1;

const int _GLIBCXX_HAVE_LOGF = 1;

const int _GLIBCXX_HAVE_LOGL = 1;

const int _GLIBCXX_HAVE_MBSTATE_T = 1;

const int _GLIBCXX_HAVE_MEMALIGN = 1;

const int _GLIBCXX_HAVE_MEMORY_H = 1;

const int _GLIBCXX_HAVE_MODF = 1;

const int _GLIBCXX_HAVE_MODFF = 1;

const int _GLIBCXX_HAVE_MODFL = 1;

const int _GLIBCXX_HAVE_NETDB_H = 1;

const int _GLIBCXX_HAVE_NETINET_IN_H = 1;

const int _GLIBCXX_HAVE_NETINET_TCP_H = 1;

const int _GLIBCXX_HAVE_OPENAT = 1;

const int _GLIBCXX_HAVE_POLL = 1;

const int _GLIBCXX_HAVE_POLL_H = 1;

const int _GLIBCXX_HAVE_POSIX_MEMALIGN = 1;

const int _GLIBCXX_HAVE_POSIX_SEMAPHORE = 1;

const int _GLIBCXX_HAVE_POWF = 1;

const int _GLIBCXX_HAVE_POWL = 1;

const int _GLIBCXX_HAVE_QUICK_EXIT = 1;

const int _GLIBCXX_HAVE_READLINK = 1;

const int _GLIBCXX_HAVE_SECURE_GETENV = 1;

const int _GLIBCXX_HAVE_SETENV = 1;

const int _GLIBCXX_HAVE_SINCOS = 1;

const int _GLIBCXX_HAVE_SINCOSF = 1;

const int _GLIBCXX_HAVE_SINCOSL = 1;

const int _GLIBCXX_HAVE_SINF = 1;

const int _GLIBCXX_HAVE_SINHF = 1;

const int _GLIBCXX_HAVE_SINHL = 1;

const int _GLIBCXX_HAVE_SINL = 1;

const int _GLIBCXX_HAVE_SOCKATMARK = 1;

const int _GLIBCXX_HAVE_SQRTF = 1;

const int _GLIBCXX_HAVE_SQRTL = 1;

const int _GLIBCXX_HAVE_STDALIGN_H = 1;

const int _GLIBCXX_HAVE_STDBOOL_H = 1;

const int _GLIBCXX_HAVE_STDINT_H = 1;

const int _GLIBCXX_HAVE_STDLIB_H = 1;

const int _GLIBCXX_HAVE_STRERROR_L = 1;

const int _GLIBCXX_HAVE_STRERROR_R = 1;

const int _GLIBCXX_HAVE_STRINGS_H = 1;

const int _GLIBCXX_HAVE_STRING_H = 1;

const int _GLIBCXX_HAVE_STRTOF = 1;

const int _GLIBCXX_HAVE_STRTOLD = 1;

const int _GLIBCXX_HAVE_STRUCT_DIRENT_D_TYPE = 1;

const int _GLIBCXX_HAVE_STRXFRM_L = 1;

const int _GLIBCXX_HAVE_SYMLINK = 1;

const int _GLIBCXX_HAVE_SYMVER_SYMBOL_RENAMING_RUNTIME_SUPPORT = 1;

const int _GLIBCXX_HAVE_SYS_IOCTL_H = 1;

const int _GLIBCXX_HAVE_SYS_IPC_H = 1;

const int _GLIBCXX_HAVE_SYS_PARAM_H = 1;

const int _GLIBCXX_HAVE_SYS_RESOURCE_H = 1;

const int _GLIBCXX_HAVE_SYS_SDT_H = 1;

const int _GLIBCXX_HAVE_SYS_SEM_H = 1;

const int _GLIBCXX_HAVE_SYS_SOCKET_H = 1;

const int _GLIBCXX_HAVE_SYS_STATVFS_H = 1;

const int _GLIBCXX_HAVE_SYS_STAT_H = 1;

const int _GLIBCXX_HAVE_SYS_SYSINFO_H = 1;

const int _GLIBCXX_HAVE_SYS_TIME_H = 1;

const int _GLIBCXX_HAVE_SYS_TYPES_H = 1;

const int _GLIBCXX_HAVE_SYS_UIO_H = 1;

const int _GLIBCXX_HAVE_S_ISREG = 1;

const int _GLIBCXX_HAVE_TANF = 1;

const int _GLIBCXX_HAVE_TANHF = 1;

const int _GLIBCXX_HAVE_TANHL = 1;

const int _GLIBCXX_HAVE_TANL = 1;

const int _GLIBCXX_HAVE_TGMATH_H = 1;

const int _GLIBCXX_HAVE_TIMESPEC_GET = 1;

const int _GLIBCXX_HAVE_TLS = 1;

const int _GLIBCXX_HAVE_TRUNCATE = 1;

const int _GLIBCXX_HAVE_UCHAR_H = 1;

const int _GLIBCXX_HAVE_UNISTD_H = 1;

const int _GLIBCXX_HAVE_UNLINKAT = 1;

const int _GLIBCXX_HAVE_USELOCALE = 1;

const int _GLIBCXX_HAVE_UTIME_H = 1;

const int _GLIBCXX_HAVE_VFWSCANF = 1;

const int _GLIBCXX_HAVE_VSWSCANF = 1;

const int _GLIBCXX_HAVE_VWSCANF = 1;

const int _GLIBCXX_HAVE_WCHAR_H = 1;

const int _GLIBCXX_HAVE_WCSTOF = 1;

const int _GLIBCXX_HAVE_WCTYPE_H = 1;

const int _GLIBCXX_HAVE_WRITEV = 1;

const int _GLIBCXX_HAVE___CXA_THREAD_ATEXIT_IMPL = 1;

const String _GLIBCXX_LT_OBJDIR = '.libs/';

const String _GLIBCXX_PACKAGE_BUGREPORT = '';

const String _GLIBCXX_PACKAGE_NAME = 'package-unused';

const String _GLIBCXX_PACKAGE_STRING = 'package-unused version-unused';

const String _GLIBCXX_PACKAGE_TARNAME = 'libstdc++';

const String _GLIBCXX_PACKAGE_URL = '';

const String _GLIBCXX_PACKAGE__GLIBCXX_VERSION = 'version-unused';

const int _GLIBCXX_STDC_HEADERS = 1;

const int _GLIBCXX_DARWIN_USE_64_BIT_INODE = 1;

const int _GLIBCXX11_USE_C99_COMPLEX = 1;

const int _GLIBCXX11_USE_C99_MATH = 1;

const int _GLIBCXX11_USE_C99_STDIO = 1;

const int _GLIBCXX11_USE_C99_STDLIB = 1;

const int _GLIBCXX11_USE_C99_WCHAR = 1;

const int _GLIBCXX98_USE_C99_COMPLEX = 1;

const int _GLIBCXX98_USE_C99_MATH = 1;

const int _GLIBCXX98_USE_C99_STDIO = 1;

const int _GLIBCXX98_USE_C99_STDLIB = 1;

const int _GLIBCXX98_USE_C99_WCHAR = 1;

const int _GLIBCXX_ATOMIC_BUILTINS = 1;

const int _GLIBCXX_CAN_ALIGNAS_DESTRUCTIVE_SIZE = 1;

const int _GLIBCXX_FULLY_DYNAMIC_STRING = 0;

const int _GLIBCXX_HAS_GTHREADS = 1;

const int _GLIBCXX_HOSTED = 1;

const int _GLIBCXX_RES_LIMITS = 1;

const int _GLIBCXX_STATIC_TZDATA = 1;

const int _GLIBCXX_STDIO_EOF = -1;

const int _GLIBCXX_STDIO_SEEK_CUR = 1;

const int _GLIBCXX_STDIO_SEEK_END = 2;

const int _GLIBCXX_SYMVER = 1;

const int _GLIBCXX_SYMVER_GNU = 1;

const int _GLIBCXX_USE_C11_UCHAR_CXX11 = 1;

const int _GLIBCXX_USE_C99 = 1;

const int _GLIBCXX_USE_C99_COMPLEX_TR1 = 1;

const int _GLIBCXX_USE_C99_CTYPE_TR1 = 1;

const int _GLIBCXX_USE_C99_FENV_TR1 = 1;

const int _GLIBCXX_USE_C99_INTTYPES_TR1 = 1;

const int _GLIBCXX_USE_C99_INTTYPES_WCHAR_T_TR1 = 1;

const int _GLIBCXX_USE_C99_MATH_TR1 = 1;

const int _GLIBCXX_USE_C99_STDINT_TR1 = 1;

const int _GLIBCXX_USE_CLOCK_MONOTONIC = 1;

const int _GLIBCXX_USE_CLOCK_REALTIME = 1;

const int _GLIBCXX_USE_DECIMAL_FLOAT = 1;

const int _GLIBCXX_USE_DEV_RANDOM = 1;

const int _GLIBCXX_USE_FCHMOD = 1;

const int _GLIBCXX_USE_FCHMODAT = 1;

const int _GLIBCXX_USE_FSEEKO_FTELLO = 1;

const int _GLIBCXX_USE_GETTIMEOFDAY = 1;

const int _GLIBCXX_USE_GET_NPROCS = 1;

const int _GLIBCXX_USE_INIT_PRIORITY_ATTRIBUTE = 1;

const int _GLIBCXX_USE_LFS = 1;

const int _GLIBCXX_USE_LONG_LONG = 1;

const int _GLIBCXX_USE_LSTAT = 1;

const int _GLIBCXX_USE_NANOSLEEP = 1;

const int _GLIBCXX_USE_NLS = 1;

const int _GLIBCXX_USE_PTHREAD_COND_CLOCKWAIT = 1;

const int _GLIBCXX_USE_PTHREAD_MUTEX_CLOCKLOCK = 1;

const int _GLIBCXX_USE_PTHREAD_RWLOCK_CLOCKLOCK = 1;

const int _GLIBCXX_USE_PTHREAD_RWLOCK_T = 1;

const int _GLIBCXX_USE_RANDOM_TR1 = 1;

const int _GLIBCXX_USE_REALPATH = 1;

const int _GLIBCXX_USE_SCHED_YIELD = 1;

const int _GLIBCXX_USE_SC_NPROCESSORS_ONLN = 1;

const int _GLIBCXX_USE_SENDFILE = 1;

const int _GLIBCXX_USE_ST_MTIM = 1;

const int _GLIBCXX_USE_TMPNAM = 1;

const int _GLIBCXX_USE_UCHAR_C8RTOMB_MBRTOC8_CXX20 = 1;

const int _GLIBCXX_USE_UCHAR_C8RTOMB_MBRTOC8_FCHAR8_T = 1;

const int _GLIBCXX_USE_UTIME = 1;

const int _GLIBCXX_USE_UTIMENSAT = 1;

const int _GLIBCXX_USE_WCHAR_T = 1;

const int _GLIBCXX_VERBOSE = 1;

const int _GLIBCXX_X86_RDRAND = 1;

const int _GLIBCXX_X86_RDSEED = 1;

const String _GLIBCXX_ZONEINFO_DIR = '/usr/share/zoneinfo';

const int _GTHREAD_USE_MUTEX_TIMEDLOCK = 1;

const int _GLIBCXX_OSTREAM = 1;

const int _GLIBCXX_IOS = 1;

const int _GLIBCXX_IOSFWD = 1;

const int _STRINGFWD_H = 1;

const int _MEMORYFWD_H = 1;

const int _GLIBCXX_POSTYPES_H = 1;

const int _WCHAR_H = 1;

const int __GLIBC_USE_LIB_EXT2 = 1;

const int __GLIBC_USE_IEC_60559_BFP_EXT = 1;

const int __GLIBC_USE_IEC_60559_BFP_EXT_C2X = 1;

const int __GLIBC_USE_IEC_60559_EXT = 1;

const int __GLIBC_USE_IEC_60559_FUNCS_EXT = 1;

const int __GLIBC_USE_IEC_60559_FUNCS_EXT_C2X = 1;

const int __GLIBC_USE_IEC_60559_TYPES_EXT = 1;

const int __HAVE_FLOAT128 = 0;

const int __HAVE_DISTINCT_FLOAT128 = 0;

const int __HAVE_FLOAT64X = 1;

const int __HAVE_FLOAT64X_LONG_DOUBLE = 1;

const int __HAVE_FLOAT16 = 0;

const int __HAVE_FLOAT32 = 1;

const int __HAVE_FLOAT64 = 1;

const int __HAVE_FLOAT32X = 1;

const int __HAVE_FLOAT128X = 0;

const int __HAVE_DISTINCT_FLOAT16 = 0;

const int __HAVE_DISTINCT_FLOAT32 = 0;

const int __HAVE_DISTINCT_FLOAT64 = 0;

const int __HAVE_DISTINCT_FLOAT32X = 0;

const int __HAVE_DISTINCT_FLOAT64X = 0;

const int __HAVE_DISTINCT_FLOAT128X = 0;

const int __HAVE_FLOAT128_UNLIKE_LDBL = 0;

const int __HAVE_FLOATN_NOT_TYPEDEF = 0;

const int NULL = 0;

const int _BITS_WCHAR_H = 1;

const int __WCHAR_MAX = 2147483647;

const int __WCHAR_MIN = -2147483648;

const int __wint_t_defined = 1;

const int _WINT_T = 1;

const int __mbstate_t_defined = 1;

const int ____mbstate_t_defined = 1;

const int ____FILE_defined = 1;

const int __FILE_defined = 1;

const int _BITS_TYPES_LOCALE_T_H = 1;

const int _BITS_TYPES___LOCALE_T_H = 1;

const int WCHAR_MIN = -2147483648;

const int WCHAR_MAX = 2147483647;

const int WEOF = 4294967295;

const int _GLIBCXX_CWCHAR = 1;

const int __EXCEPTION_H = 1;

const int __cpp_lib_uncaught_exceptions = 201411;

const int _EXCEPTION_DEFINES_H = 1;

const int _CXXABI_INIT_EXCEPTION_H = 1;

const int _GLIBCXX_HAVE_CDTOR_CALLABI = 0;

const int _HASH_BYTES_H = 1;

const int __GXX_MERGED_TYPEINFO_NAMES = 0;

const int __GXX_TYPEINFO_EQUALITY_INLINE = 1;

const int __cpp_lib_launder = 201606;

const int _MOVE_H = 1;

const int _GLIBCXX_TYPE_TRAITS = 1;

const int __cpp_lib_integral_constant_callable = 201304;

const int __cpp_lib_bool_constant = 201505;

const int __cpp_lib_logical_traits = 201510;

const int __cpp_lib_is_null_pointer = 201309;

const int __cpp_lib_is_final = 201402;

const int __cpp_lib_transformation_trait_aliases = 201304;

const int __cpp_lib_result_of_sfinae = 201210;

const int __cpp_lib_void_t = 201411;

const int __cpp_lib_is_swappable = 201603;

const int __cpp_lib_is_invocable = 201703;

const int __cpp_lib_type_trait_variable_templates = 201510;

const int __cpp_lib_has_unique_object_representations = 201606;

const int __cpp_lib_is_aggregate = 201703;

const int __cpp_lib_addressof_constexpr = 201603;

const int _GLIBCXX_NESTED_EXCEPTION_H = 1;

const int _CHAR_TRAITS_H = 1;

const int __cpp_lib_constexpr_char_traits = 201611;

const int _LOCALE_FWD_H = 1;

const int _GLIBCXX_CXX_LOCALE_H = 1;

const int _LOCALE_H = 1;

const int _BITS_LOCALE_H = 1;

const int __LC_CTYPE = 0;

const int __LC_NUMERIC = 1;

const int __LC_TIME = 2;

const int __LC_COLLATE = 3;

const int __LC_MONETARY = 4;

const int __LC_MESSAGES = 5;

const int __LC_ALL = 6;

const int __LC_PAPER = 7;

const int __LC_NAME = 8;

const int __LC_ADDRESS = 9;

const int __LC_TELEPHONE = 10;

const int __LC_MEASUREMENT = 11;

const int __LC_IDENTIFICATION = 12;

const int LC_CTYPE = 0;

const int LC_NUMERIC = 1;

const int LC_TIME = 2;

const int LC_COLLATE = 3;

const int LC_MONETARY = 4;

const int LC_MESSAGES = 5;

const int LC_ALL = 6;

const int LC_PAPER = 7;

const int LC_NAME = 8;

const int LC_ADDRESS = 9;

const int LC_TELEPHONE = 10;

const int LC_MEASUREMENT = 11;

const int LC_IDENTIFICATION = 12;

const int LC_CTYPE_MASK = 1;

const int LC_NUMERIC_MASK = 2;

const int LC_TIME_MASK = 4;

const int LC_COLLATE_MASK = 8;

const int LC_MONETARY_MASK = 16;

const int LC_MESSAGES_MASK = 32;

const int LC_PAPER_MASK = 128;

const int LC_NAME_MASK = 256;

const int LC_ADDRESS_MASK = 512;

const int LC_TELEPHONE_MASK = 1024;

const int LC_MEASUREMENT_MASK = 2048;

const int LC_IDENTIFICATION_MASK = 4096;

const int LC_ALL_MASK = 8127;

const int _GLIBCXX_CLOCALE = 1;

const int _GLIBCXX_C_LOCALE_GNU = 1;

const int _GLIBCXX_NUM_CATEGORIES = 6;

const int _CTYPE_H = 1;

const int _BITS_TYPES_H = 1;

const int _BITS_TYPESIZES_H = 1;

const int __OFF_T_MATCHES_OFF64_T = 1;

const int __INO_T_MATCHES_INO64_T = 1;

const int __RLIM_T_MATCHES_RLIM64_T = 1;

const int __STATFS_MATCHES_STATFS64 = 1;

const int __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64 = 1;

const int __FD_SETSIZE = 1024;

const int _BITS_TIME64_H = 1;

const int _BITS_ENDIAN_H = 1;

const int __LITTLE_ENDIAN = 1234;

const int __BIG_ENDIAN = 4321;

const int __PDP_ENDIAN = 3412;

const int _BITS_ENDIANNESS_H = 1;

const int __BYTE_ORDER = 1234;

const int __FLOAT_WORD_ORDER = 1234;

const int _GLIBCXX_CCTYPE = 1;

const int _IOS_BASE_H = 1;

const int _GLIBCXX_ATOMICITY_H = 1;

const int __GTHREADS = 1;

const int __GTHREADS_CXX0X = 1;

const int _PTHREAD_H = 1;

const int _SCHED_H = 1;

const int __time_t_defined = 1;

const int _STRUCT_TIMESPEC = 1;

const int _BITS_SCHED_H = 1;

const int SCHED_OTHER = 0;

const int SCHED_FIFO = 1;

const int SCHED_RR = 2;

const int SCHED_BATCH = 3;

const int SCHED_ISO = 4;

const int SCHED_IDLE = 5;

const int SCHED_DEADLINE = 6;

const int SCHED_RESET_ON_FORK = 1073741824;

const int CSIGNAL = 255;

const int CLONE_VM = 256;

const int CLONE_FS = 512;

const int CLONE_FILES = 1024;

const int CLONE_SIGHAND = 2048;

const int CLONE_PIDFD = 4096;

const int CLONE_PTRACE = 8192;

const int CLONE_VFORK = 16384;

const int CLONE_PARENT = 32768;

const int CLONE_THREAD = 65536;

const int CLONE_NEWNS = 131072;

const int CLONE_SYSVSEM = 262144;

const int CLONE_SETTLS = 524288;

const int CLONE_PARENT_SETTID = 1048576;

const int CLONE_CHILD_CLEARTID = 2097152;

const int CLONE_DETACHED = 4194304;

const int CLONE_UNTRACED = 8388608;

const int CLONE_CHILD_SETTID = 16777216;

const int CLONE_NEWCGROUP = 33554432;

const int CLONE_NEWUTS = 67108864;

const int CLONE_NEWIPC = 134217728;

const int CLONE_NEWUSER = 268435456;

const int CLONE_NEWPID = 536870912;

const int CLONE_NEWNET = 1073741824;

const int CLONE_IO = 2147483648;

const int CLONE_NEWTIME = 128;

const int _BITS_TYPES_STRUCT_SCHED_PARAM = 1;

const int _BITS_CPU_SET_H = 1;

const int __CPU_SETSIZE = 1024;

const int __NCPUBITS = 64;

const int CPU_SETSIZE = 1024;

const int _TIME_H = 1;

const int _BITS_TIME_H = 1;

const int CLOCKS_PER_SEC = 1000000;

const int CLOCK_REALTIME = 0;

const int CLOCK_MONOTONIC = 1;

const int CLOCK_PROCESS_CPUTIME_ID = 2;

const int CLOCK_THREAD_CPUTIME_ID = 3;

const int CLOCK_MONOTONIC_RAW = 4;

const int CLOCK_REALTIME_COARSE = 5;

const int CLOCK_MONOTONIC_COARSE = 6;

const int CLOCK_BOOTTIME = 7;

const int CLOCK_REALTIME_ALARM = 8;

const int CLOCK_BOOTTIME_ALARM = 9;

const int CLOCK_TAI = 11;

const int TIMER_ABSTIME = 1;

const int _BITS_TIMEX_H = 1;

const int __timeval_defined = 1;

const int ADJ_OFFSET = 1;

const int ADJ_FREQUENCY = 2;

const int ADJ_MAXERROR = 4;

const int ADJ_ESTERROR = 8;

const int ADJ_STATUS = 16;

const int ADJ_TIMECONST = 32;

const int ADJ_TAI = 128;

const int ADJ_SETOFFSET = 256;

const int ADJ_MICRO = 4096;

const int ADJ_NANO = 8192;

const int ADJ_TICK = 16384;

const int ADJ_OFFSET_SINGLESHOT = 32769;

const int ADJ_OFFSET_SS_READ = 40961;

const int MOD_OFFSET = 1;

const int MOD_FREQUENCY = 2;

const int MOD_MAXERROR = 4;

const int MOD_ESTERROR = 8;

const int MOD_STATUS = 16;

const int MOD_TIMECONST = 32;

const int MOD_CLKB = 16384;

const int MOD_CLKA = 32769;

const int MOD_TAI = 128;

const int MOD_MICRO = 4096;

const int MOD_NANO = 8192;

const int STA_PLL = 1;

const int STA_PPSFREQ = 2;

const int STA_PPSTIME = 4;

const int STA_FLL = 8;

const int STA_INS = 16;

const int STA_DEL = 32;

const int STA_UNSYNC = 64;

const int STA_FREQHOLD = 128;

const int STA_PPSSIGNAL = 256;

const int STA_PPSJITTER = 512;

const int STA_PPSWANDER = 1024;

const int STA_PPSERROR = 2048;

const int STA_CLOCKERR = 4096;

const int STA_NANO = 8192;

const int STA_MODE = 16384;

const int STA_CLK = 32768;

const int STA_RONLY = 65280;

const int __clock_t_defined = 1;

const int __struct_tm_defined = 1;

const int __clockid_t_defined = 1;

const int __timer_t_defined = 1;

const int __itimerspec_defined = 1;

const int TIME_UTC = 1;

const int _BITS_PTHREADTYPES_COMMON_H = 1;

const int _THREAD_SHARED_TYPES_H = 1;

const int _BITS_PTHREADTYPES_ARCH_H = 1;

const int __SIZEOF_PTHREAD_MUTEX_T = 40;

const int __SIZEOF_PTHREAD_ATTR_T = 56;

const int __SIZEOF_PTHREAD_RWLOCK_T = 56;

const int __SIZEOF_PTHREAD_BARRIER_T = 32;

const int __SIZEOF_PTHREAD_MUTEXATTR_T = 4;

const int __SIZEOF_PTHREAD_COND_T = 48;

const int __SIZEOF_PTHREAD_CONDATTR_T = 4;

const int __SIZEOF_PTHREAD_RWLOCKATTR_T = 8;

const int __SIZEOF_PTHREAD_BARRIERATTR_T = 4;

const int _THREAD_MUTEX_INTERNAL_H = 1;

const int __PTHREAD_MUTEX_HAVE_PREV = 1;

const int __PTHREAD_RWLOCK_ELISION_EXTRA = 0;

const int __have_pthread_attr_t = 1;

const int _BITS_SETJMP_H = 1;

const int _SIGSET_NWORDS = 16;

const int __jmp_buf_tag_defined = 1;

const int __SC_THREAD_STACK_MIN_VALUE = 75;

const int PTHREAD_CREATE_JOINABLE1 = 0;

const int PTHREAD_CREATE_DETACHED1 = 1;

const int PTHREAD_INHERIT_SCHED1 = 0;

const int PTHREAD_EXPLICIT_SCHED1 = 1;

const int PTHREAD_SCOPE_SYSTEM1 = 0;

const int PTHREAD_SCOPE_PROCESS1 = 1;

const int PTHREAD_PROCESS_PRIVATE1 = 0;

const int PTHREAD_PROCESS_SHARED1 = 1;

const int PTHREAD_CANCEL_ENABLE1 = 0;

const int PTHREAD_CANCEL_DISABLE1 = 1;

const int PTHREAD_CANCEL_DEFERRED1 = 0;

const int PTHREAD_CANCEL_ASYNCHRONOUS1 = 1;

const int PTHREAD_ONCE_INIT = 0;

const int PTHREAD_BARRIER_SERIAL_THREAD = -1;

const int PTHREAD_ATTR_NO_SIGMASK_NP = -1;

const int __GTHREAD_HAS_COND = 1;

const int __GTHREAD_ONCE_INIT = 0;

const int _GLIBCXX_ATOMIC_WORD_H = 1;

const int _LOCALE_CLASSES_H = 1;

const int _GLIBCXX_STRING = 1;

const int _ALLOCATOR_H = 1;

const int _GLIBCXX_CXX_ALLOCATOR_H = 1;

const int _STD_NEW_ALLOCATOR_H = 1;

const int _FUNCTEXCEPT_H = 1;

const int __cpp_lib_incomplete_container_elements = 201505;

const int _CPP_TYPE_TRAITS_H = 1;

const int _OSTREAM_INSERT_H = 1;

const int _CXXABI_FORCED_H = 1;

const int _STL_ITERATOR_BASE_FUNCS_H = 1;

const int _CONCEPT_CHECK_H = 1;

const int _GLIBCXX_DEBUG_ASSERTIONS_H = 1;

const int _STL_ITERATOR_BASE_TYPES_H = 1;

const int _STL_ITERATOR_H = 1;

const int _EXT_TYPE_TRAITS = 1;

const int _PTR_TRAITS_H = 1;

const int __cpp_lib_array_constexpr = 201803;

const int __cpp_lib_make_reverse_iterator = 201402;

const int _STL_FUNCTION_H = 1;

const int __cpp_lib_transparent_operators = 201510;

const int _BACKWARD_BINDERS_H = 1;

const int _EXT_NUMERIC_TRAITS = 1;

const int _STL_ALGOBASE_H = 1;

const int _STL_PAIR_H = 1;

const int _GLIBCXX_UTILITY_H = 1;

const int __cpp_lib_tuple_element_t = 201402;

const int __cpp_lib_integer_sequence = 201304;

const int __cpp_lib_tuples_by_type = 201304;

const int _GLIBCXX_DEBUG_MACRO_SWITCH_H = 1;

const int _GLIBCXX_PREDEFINED_OPS_H = 1;

const int _GLIBCXX_BIT = 1;

const int __cpp_lib_robust_nonmodifying_seq_ops = 201304;

const int _GLIBCXX_REFWRAP_H = 1;

const int _GLIBCXX_INVOKE_H = 1;

const int _GLIBCXX_RANGE_ACCESS_H = 1;

const int __cpp_lib_nonmember_container_access = 201411;

const int _BASIC_STRING_H = 1;

const int _EXT_ALLOC_TRAITS_H = 1;

const int _ALLOC_TRAITS_H = 1;

const int _STL_CONSTRUCT_H = 1;

const int __cpp_lib_allocator_traits_is_always_equal = 201411;

const int _GLIBCXX_STRING_VIEW = 1;

const int _FUNCTIONAL_HASH_H = 1;

const int __cpp_lib_string_view = 201803;

const int _GLIBCXX_STRING_VIEW_TCC = 1;

const int __cpp_lib_constexpr_string = 201611;

const int _STRING_CONVERSIONS_H = 1;

const int _GLIBCXX_CSTDLIB = 1;

const int _STDLIB_H = 1;

const int WNOHANG = 1;

const int WUNTRACED = 2;

const int WSTOPPED = 2;

const int WEXITED = 4;

const int WCONTINUED = 8;

const int WNOWAIT = 16777216;

const int __WNOTHREAD = 536870912;

const int __WALL = 1073741824;

const int __WCLONE = 2147483648;

const int __W_CONTINUED = 65535;

const int __WCOREFLAG = 128;

const int __ldiv_t_defined = 1;

const int __lldiv_t_defined = 1;

const int RAND_MAX = 2147483647;

const int EXIT_FAILURE = 1;

const int EXIT_SUCCESS = 0;

const int _SYS_TYPES_H = 1;

const int _BITS_STDINT_INTN_H = 1;

const int __BIT_TYPES_DEFINED__ = 1;

const int _ENDIAN_H = 1;

const int LITTLE_ENDIAN = 1234;

const int BIG_ENDIAN = 4321;

const int PDP_ENDIAN = 3412;

const int BYTE_ORDER = 1234;

const int _BITS_BYTESWAP_H = 1;

const int _BITS_UINTN_IDENTITY_H = 1;

const int _SYS_SELECT_H = 1;

const int __sigset_t_defined = 1;

const int __NFDBITS = 64;

const int FD_SETSIZE = 1024;

const int NFDBITS = 64;

const int _ALLOCA_H = 1;

const int _STDIO_H = 1;

const int _____fpos_t_defined = 1;

const int _____fpos64_t_defined = 1;

const int __struct_FILE_defined = 1;

const int _IO_EOF_SEEN = 16;

const int _IO_ERR_SEEN = 32;

const int _IO_USER_LOCK = 32768;

const int __cookie_io_functions_t_defined = 1;

const int _IOFBF = 0;

const int _IOLBF = 1;

const int _IONBF = 2;

const int BUFSIZ = 8192;

const int EOF = -1;

const int SEEK_SET = 0;

const int SEEK_CUR = 1;

const int SEEK_END = 2;

const int SEEK_DATA = 3;

const int SEEK_HOLE = 4;

const String P_tmpdir = '/tmp';

const int L_tmpnam = 20;

const int TMP_MAX = 238328;

const int _BITS_STDIO_LIM_H = 1;

const int FILENAME_MAX = 4096;

const int L_ctermid = 9;

const int L_cuserid = 9;

const int FOPEN_MAX = 16;

const int _PRINTF_NAN_LEN_MAX = 4;

const int RENAME_NOREPLACE = 1;

const int RENAME_EXCHANGE = 2;

const int RENAME_WHITEOUT = 4;

const int _GLIBCXX_CSTDIO = 1;

const int _ERRNO_H = 1;

const int _BITS_ERRNO_H = 1;

const int EPERM = 1;

const int ENOENT = 2;

const int ESRCH = 3;

const int EINTR = 4;

const int EIO = 5;

const int ENXIO = 6;

const int E2BIG = 7;

const int ENOEXEC = 8;

const int EBADF = 9;

const int ECHILD = 10;

const int EAGAIN = 11;

const int ENOMEM = 12;

const int EACCES = 13;

const int EFAULT = 14;

const int ENOTBLK = 15;

const int EBUSY = 16;

const int EEXIST = 17;

const int EXDEV = 18;

const int ENODEV = 19;

const int ENOTDIR = 20;

const int EISDIR = 21;

const int EINVAL = 22;

const int ENFILE = 23;

const int EMFILE = 24;

const int ENOTTY = 25;

const int ETXTBSY = 26;

const int EFBIG = 27;

const int ENOSPC = 28;

const int ESPIPE = 29;

const int EROFS = 30;

const int EMLINK = 31;

const int EPIPE = 32;

const int EDOM = 33;

const int ERANGE = 34;

const int EDEADLK = 35;

const int ENAMETOOLONG = 36;

const int ENOLCK = 37;

const int ENOSYS = 38;

const int ENOTEMPTY = 39;

const int ELOOP = 40;

const int EWOULDBLOCK = 11;

const int ENOMSG = 42;

const int EIDRM = 43;

const int ECHRNG = 44;

const int EL2NSYNC = 45;

const int EL3HLT = 46;

const int EL3RST = 47;

const int ELNRNG = 48;

const int EUNATCH = 49;

const int ENOCSI = 50;

const int EL2HLT = 51;

const int EBADE = 52;

const int EBADR = 53;

const int EXFULL = 54;

const int ENOANO = 55;

const int EBADRQC = 56;

const int EBADSLT = 57;

const int EDEADLOCK = 35;

const int EBFONT = 59;

const int ENOSTR = 60;

const int ENODATA = 61;

const int ETIME = 62;

const int ENOSR = 63;

const int ENONET = 64;

const int ENOPKG = 65;

const int EREMOTE = 66;

const int ENOLINK = 67;

const int EADV = 68;

const int ESRMNT = 69;

const int ECOMM = 70;

const int EPROTO = 71;

const int EMULTIHOP = 72;

const int EDOTDOT = 73;

const int EBADMSG = 74;

const int EOVERFLOW = 75;

const int ENOTUNIQ = 76;

const int EBADFD = 77;

const int EREMCHG = 78;

const int ELIBACC = 79;

const int ELIBBAD = 80;

const int ELIBSCN = 81;

const int ELIBMAX = 82;

const int ELIBEXEC = 83;

const int EILSEQ = 84;

const int ERESTART = 85;

const int ESTRPIPE = 86;

const int EUSERS = 87;

const int ENOTSOCK = 88;

const int EDESTADDRREQ = 89;

const int EMSGSIZE = 90;

const int EPROTOTYPE = 91;

const int ENOPROTOOPT = 92;

const int EPROTONOSUPPORT = 93;

const int ESOCKTNOSUPPORT = 94;

const int EOPNOTSUPP = 95;

const int EPFNOSUPPORT = 96;

const int EAFNOSUPPORT = 97;

const int EADDRINUSE = 98;

const int EADDRNOTAVAIL = 99;

const int ENETDOWN = 100;

const int ENETUNREACH = 101;

const int ENETRESET = 102;

const int ECONNABORTED = 103;

const int ECONNRESET = 104;

const int ENOBUFS = 105;

const int EISCONN = 106;

const int ENOTCONN = 107;

const int ESHUTDOWN = 108;

const int ETOOMANYREFS = 109;

const int ETIMEDOUT = 110;

const int ECONNREFUSED = 111;

const int EHOSTDOWN = 112;

const int EHOSTUNREACH = 113;

const int EALREADY = 114;

const int EINPROGRESS = 115;

const int ESTALE = 116;

const int EUCLEAN = 117;

const int ENOTNAM = 118;

const int ENAVAIL = 119;

const int EISNAM = 120;

const int EREMOTEIO = 121;

const int EDQUOT = 122;

const int ENOMEDIUM = 123;

const int EMEDIUMTYPE = 124;

const int ECANCELED = 125;

const int ENOKEY = 126;

const int EKEYEXPIRED = 127;

const int EKEYREVOKED = 128;

const int EKEYREJECTED = 129;

const int EOWNERDEAD = 130;

const int ENOTRECOVERABLE = 131;

const int ERFKILL = 132;

const int EHWPOISON = 133;

const int ENOTSUP = 95;

const int __error_t_defined = 1;

const int _GLIBCXX_CERRNO = 1;

const int _GLIBCXX_CHARCONV_H = 1;

const int __cpp_lib_string_udls = 201304;

const int _BASIC_STRING_TCC = 1;

const int _GLIBCXX_MEMORY_RESOURCE_H = 1;

const int _GLIBCXX_CSTDDEF = 1;

const int __cpp_lib_byte = 201603;

const int _USES_ALLOCATOR_H = 1;

const int _USES_ALLOCATOR_ARGS = 1;

const int _GLIBCXX_TUPLE = 1;

const int __cpp_lib_apply = 201603;

const int __cpp_lib_make_from_tuple = 201606;

const int _LOCALE_CLASSES_TCC = 1;

const int _GLIBCXX_SYSTEM_ERROR = 1;

const int _GLIBCXX_ERROR_CONSTANTS = 1;

const int _GLIBCXX_STDEXCEPT = 1;

const int _GLIBXX_STREAMBUF = 1;

const int _STREAMBUF_TCC = 1;

const int _BASIC_IOS_H = 1;

const int _LOCALE_FACETS_H = 1;

const int _WCTYPE_H = 1;

const int _BITS_WCTYPE_WCHAR_H = 1;

const int _GLIBCXX_CWCTYPE = 1;

const int _STREAMBUF_ITERATOR_H = 1;

const int _GLIBCXX_NUM_FACETS = 14;

const int _GLIBCXX_NUM_CXX11_FACETS = 8;

const int _GLIBCXX_NUM_UNICODE_FACETS = 2;

const int _GLIBCXX_NUM_LBDL_ALT128_FACETS = 6;

const int _LOCALE_FACETS_TCC = 1;

const int _BASIC_IOS_TCC = 1;

const int _OSTREAM_TCC = 1;

const int _GLIBCXX_ISTREAM = 1;

const int _ISTREAM_TCC = 1;

const int _GLIBCXX_FSTREAM = 1;

const int _CODECVT_H = 1;

const int _GLIBCXX_BASIC_FILE_STDIO_H = 1;

const int _GLIBCXX_CXX_IO_H = 1;

const int _GLIBCXX_BUFSIZ = 8192;

const int _FSTREAM_TCC = 1;

const int _GLIBCXX_SSTREAM = 1;

const int _SSTREAM_TCC = 1;

const int _UNISTD_H = 1;

const int _POSIX_VERSION = 200809;

const int __POSIX2_THIS_VERSION = 200809;

const int _POSIX2_VERSION = 200809;

const int _POSIX2_C_VERSION = 200809;

const int _POSIX2_C_BIND = 200809;

const int _POSIX2_C_DEV = 200809;

const int _POSIX2_SW_DEV = 200809;

const int _POSIX2_LOCALEDEF = 200809;

const int _XOPEN_VERSION = 700;

const int _XOPEN_XCU_VERSION = 4;

const int _XOPEN_XPG2 = 1;

const int _XOPEN_XPG3 = 1;

const int _XOPEN_XPG4 = 1;

const int _XOPEN_UNIX = 1;

const int _XOPEN_ENH_I18N = 1;

const int _XOPEN_LEGACY = 1;

const int _BITS_POSIX_OPT_H = 1;

const int _POSIX_JOB_CONTROL = 1;

const int _POSIX_SAVED_IDS = 1;

const int _POSIX_PRIORITY_SCHEDULING = 200809;

const int _POSIX_SYNCHRONIZED_IO = 200809;

const int _POSIX_FSYNC = 200809;

const int _POSIX_MAPPED_FILES = 200809;

const int _POSIX_MEMLOCK = 200809;

const int _POSIX_MEMLOCK_RANGE = 200809;

const int _POSIX_MEMORY_PROTECTION = 200809;

const int _POSIX_CHOWN_RESTRICTED = 0;

const int _POSIX_VDISABLE = 0;

const int _POSIX_NO_TRUNC = 1;

const int _XOPEN_REALTIME = 1;

const int _XOPEN_REALTIME_THREADS = 1;

const int _XOPEN_SHM = 1;

const int _POSIX_THREADS = 200809;

const int _POSIX_REENTRANT_FUNCTIONS = 1;

const int _POSIX_THREAD_SAFE_FUNCTIONS = 200809;

const int _POSIX_THREAD_PRIORITY_SCHEDULING = 200809;

const int _POSIX_THREAD_ATTR_STACKSIZE = 200809;

const int _POSIX_THREAD_ATTR_STACKADDR = 200809;

const int _POSIX_THREAD_PRIO_INHERIT = 200809;

const int _POSIX_THREAD_PRIO_PROTECT = 200809;

const int _POSIX_THREAD_ROBUST_PRIO_INHERIT = 200809;

const int _POSIX_THREAD_ROBUST_PRIO_PROTECT = -1;

const int _POSIX_SEMAPHORES = 200809;

const int _POSIX_REALTIME_SIGNALS = 200809;

const int _POSIX_ASYNCHRONOUS_IO = 200809;

const int _POSIX_ASYNC_IO = 1;

const int _LFS_ASYNCHRONOUS_IO = 1;

const int _POSIX_PRIORITIZED_IO = 200809;

const int _LFS64_ASYNCHRONOUS_IO = 1;

const int _LFS_LARGEFILE = 1;

const int _LFS64_LARGEFILE = 1;

const int _LFS64_STDIO = 1;

const int _POSIX_SHARED_MEMORY_OBJECTS = 200809;

const int _POSIX_CPUTIME = 0;

const int _POSIX_THREAD_CPUTIME = 0;

const int _POSIX_REGEXP = 1;

const int _POSIX_READER_WRITER_LOCKS = 200809;

const int _POSIX_SHELL = 1;

const int _POSIX_TIMEOUTS = 200809;

const int _POSIX_SPIN_LOCKS = 200809;

const int _POSIX_SPAWN = 200809;

const int _POSIX_TIMERS = 200809;

const int _POSIX_BARRIERS = 200809;

const int _POSIX_MESSAGE_PASSING = 200809;

const int _POSIX_THREAD_PROCESS_SHARED = 200809;

const int _POSIX_MONOTONIC_CLOCK = 0;

const int _POSIX_CLOCK_SELECTION = 200809;

const int _POSIX_ADVISORY_INFO = 200809;

const int _POSIX_IPV6 = 200809;

const int _POSIX_RAW_SOCKETS = 200809;

const int _POSIX2_CHAR_TERM = 200809;

const int _POSIX_SPORADIC_SERVER = -1;

const int _POSIX_THREAD_SPORADIC_SERVER = -1;

const int _POSIX_TRACE = -1;

const int _POSIX_TRACE_EVENT_FILTER = -1;

const int _POSIX_TRACE_INHERIT = -1;

const int _POSIX_TRACE_LOG = -1;

const int _POSIX_TYPED_MEMORY_OBJECTS = -1;

const int _POSIX_V7_LPBIG_OFFBIG = -1;

const int _POSIX_V6_LPBIG_OFFBIG = -1;

const int _XBS5_LPBIG_OFFBIG = -1;

const int _POSIX_V7_LP64_OFF64 = 1;

const int _POSIX_V6_LP64_OFF64 = 1;

const int _XBS5_LP64_OFF64 = 1;

const String __ILP32_OFF32_CFLAGS = '-m32';

const String __ILP32_OFF32_LDFLAGS = '-m32';

const String __ILP32_OFFBIG_CFLAGS =
    '-m32 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64';

const String __ILP32_OFFBIG_LDFLAGS = '-m32';

const String __LP64_OFF64_CFLAGS = '-m64';

const String __LP64_OFF64_LDFLAGS = '-m64';

const int STDIN_FILENO = 0;

const int STDOUT_FILENO = 1;

const int STDERR_FILENO = 2;

const int R_OK = 4;

const int W_OK = 2;

const int X_OK = 1;

const int F_OK = 0;

const int L_SET = 0;

const int L_INCR = 1;

const int L_XTND = 2;

const int _PC_LINK_MAX = 0;

const int _PC_MAX_CANON = 1;

const int _PC_MAX_INPUT = 2;

const int _PC_NAME_MAX = 3;

const int _PC_PATH_MAX = 4;

const int _PC_PIPE_BUF = 5;

const int _PC_CHOWN_RESTRICTED = 6;

const int _PC_NO_TRUNC = 7;

const int _PC_VDISABLE = 8;

const int _PC_SYNC_IO = 9;

const int _PC_ASYNC_IO = 10;

const int _PC_PRIO_IO = 11;

const int _PC_SOCK_MAXBUF = 12;

const int _PC_FILESIZEBITS = 13;

const int _PC_REC_INCR_XFER_SIZE = 14;

const int _PC_REC_MAX_XFER_SIZE = 15;

const int _PC_REC_MIN_XFER_SIZE = 16;

const int _PC_REC_XFER_ALIGN = 17;

const int _PC_ALLOC_SIZE_MIN = 18;

const int _PC_SYMLINK_MAX = 19;

const int _PC_2_SYMLINKS = 20;

const int _SC_ARG_MAX = 0;

const int _SC_CHILD_MAX = 1;

const int _SC_CLK_TCK = 2;

const int _SC_NGROUPS_MAX = 3;

const int _SC_OPEN_MAX = 4;

const int _SC_STREAM_MAX = 5;

const int _SC_TZNAME_MAX = 6;

const int _SC_JOB_CONTROL = 7;

const int _SC_SAVED_IDS = 8;

const int _SC_REALTIME_SIGNALS = 9;

const int _SC_PRIORITY_SCHEDULING = 10;

const int _SC_TIMERS = 11;

const int _SC_ASYNCHRONOUS_IO = 12;

const int _SC_PRIORITIZED_IO = 13;

const int _SC_SYNCHRONIZED_IO = 14;

const int _SC_FSYNC = 15;

const int _SC_MAPPED_FILES = 16;

const int _SC_MEMLOCK = 17;

const int _SC_MEMLOCK_RANGE = 18;

const int _SC_MEMORY_PROTECTION = 19;

const int _SC_MESSAGE_PASSING = 20;

const int _SC_SEMAPHORES = 21;

const int _SC_SHARED_MEMORY_OBJECTS = 22;

const int _SC_AIO_LISTIO_MAX = 23;

const int _SC_AIO_MAX = 24;

const int _SC_AIO_PRIO_DELTA_MAX = 25;

const int _SC_DELAYTIMER_MAX = 26;

const int _SC_MQ_OPEN_MAX = 27;

const int _SC_MQ_PRIO_MAX = 28;

const int _SC_VERSION = 29;

const int _SC_PAGESIZE = 30;

const int _SC_PAGE_SIZE = 30;

const int _SC_RTSIG_MAX = 31;

const int _SC_SEM_NSEMS_MAX = 32;

const int _SC_SEM_VALUE_MAX = 33;

const int _SC_SIGQUEUE_MAX = 34;

const int _SC_TIMER_MAX = 35;

const int _SC_BC_BASE_MAX = 36;

const int _SC_BC_DIM_MAX = 37;

const int _SC_BC_SCALE_MAX = 38;

const int _SC_BC_STRING_MAX = 39;

const int _SC_COLL_WEIGHTS_MAX = 40;

const int _SC_EQUIV_CLASS_MAX = 41;

const int _SC_EXPR_NEST_MAX = 42;

const int _SC_LINE_MAX = 43;

const int _SC_RE_DUP_MAX = 44;

const int _SC_CHARCLASS_NAME_MAX = 45;

const int _SC_2_VERSION = 46;

const int _SC_2_C_BIND = 47;

const int _SC_2_C_DEV = 48;

const int _SC_2_FORT_DEV = 49;

const int _SC_2_FORT_RUN = 50;

const int _SC_2_SW_DEV = 51;

const int _SC_2_LOCALEDEF = 52;

const int _SC_PII = 53;

const int _SC_PII_XTI = 54;

const int _SC_PII_SOCKET = 55;

const int _SC_PII_INTERNET = 56;

const int _SC_PII_OSI = 57;

const int _SC_POLL = 58;

const int _SC_SELECT = 59;

const int _SC_UIO_MAXIOV = 60;

const int _SC_IOV_MAX = 60;

const int _SC_PII_INTERNET_STREAM = 61;

const int _SC_PII_INTERNET_DGRAM = 62;

const int _SC_PII_OSI_COTS = 63;

const int _SC_PII_OSI_CLTS = 64;

const int _SC_PII_OSI_M = 65;

const int _SC_T_IOV_MAX = 66;

const int _SC_THREADS = 67;

const int _SC_THREAD_SAFE_FUNCTIONS = 68;

const int _SC_GETGR_R_SIZE_MAX = 69;

const int _SC_GETPW_R_SIZE_MAX = 70;

const int _SC_LOGIN_NAME_MAX = 71;

const int _SC_TTY_NAME_MAX = 72;

const int _SC_THREAD_DESTRUCTOR_ITERATIONS = 73;

const int _SC_THREAD_KEYS_MAX = 74;

const int _SC_THREAD_STACK_MIN = 75;

const int _SC_THREAD_THREADS_MAX = 76;

const int _SC_THREAD_ATTR_STACKADDR = 77;

const int _SC_THREAD_ATTR_STACKSIZE = 78;

const int _SC_THREAD_PRIORITY_SCHEDULING = 79;

const int _SC_THREAD_PRIO_INHERIT = 80;

const int _SC_THREAD_PRIO_PROTECT = 81;

const int _SC_THREAD_PROCESS_SHARED = 82;

const int _SC_NPROCESSORS_CONF = 83;

const int _SC_NPROCESSORS_ONLN = 84;

const int _SC_PHYS_PAGES = 85;

const int _SC_AVPHYS_PAGES = 86;

const int _SC_ATEXIT_MAX = 87;

const int _SC_PASS_MAX = 88;

const int _SC_XOPEN_VERSION = 89;

const int _SC_XOPEN_XCU_VERSION = 90;

const int _SC_XOPEN_UNIX = 91;

const int _SC_XOPEN_CRYPT = 92;

const int _SC_XOPEN_ENH_I18N = 93;

const int _SC_XOPEN_SHM = 94;

const int _SC_2_CHAR_TERM = 95;

const int _SC_2_C_VERSION = 96;

const int _SC_2_UPE = 97;

const int _SC_XOPEN_XPG2 = 98;

const int _SC_XOPEN_XPG3 = 99;

const int _SC_XOPEN_XPG4 = 100;

const int _SC_CHAR_BIT = 101;

const int _SC_CHAR_MAX = 102;

const int _SC_CHAR_MIN = 103;

const int _SC_INT_MAX = 104;

const int _SC_INT_MIN = 105;

const int _SC_LONG_BIT = 106;

const int _SC_WORD_BIT = 107;

const int _SC_MB_LEN_MAX = 108;

const int _SC_NZERO = 109;

const int _SC_SSIZE_MAX = 110;

const int _SC_SCHAR_MAX = 111;

const int _SC_SCHAR_MIN = 112;

const int _SC_SHRT_MAX = 113;

const int _SC_SHRT_MIN = 114;

const int _SC_UCHAR_MAX = 115;

const int _SC_UINT_MAX = 116;

const int _SC_ULONG_MAX = 117;

const int _SC_USHRT_MAX = 118;

const int _SC_NL_ARGMAX = 119;

const int _SC_NL_LANGMAX = 120;

const int _SC_NL_MSGMAX = 121;

const int _SC_NL_NMAX = 122;

const int _SC_NL_SETMAX = 123;

const int _SC_NL_TEXTMAX = 124;

const int _SC_XBS5_ILP32_OFF32 = 125;

const int _SC_XBS5_ILP32_OFFBIG = 126;

const int _SC_XBS5_LP64_OFF64 = 127;

const int _SC_XBS5_LPBIG_OFFBIG = 128;

const int _SC_XOPEN_LEGACY = 129;

const int _SC_XOPEN_REALTIME = 130;

const int _SC_XOPEN_REALTIME_THREADS = 131;

const int _SC_ADVISORY_INFO = 132;

const int _SC_BARRIERS = 133;

const int _SC_BASE = 134;

const int _SC_C_LANG_SUPPORT = 135;

const int _SC_C_LANG_SUPPORT_R = 136;

const int _SC_CLOCK_SELECTION = 137;

const int _SC_CPUTIME = 138;

const int _SC_THREAD_CPUTIME = 139;

const int _SC_DEVICE_IO = 140;

const int _SC_DEVICE_SPECIFIC = 141;

const int _SC_DEVICE_SPECIFIC_R = 142;

const int _SC_FD_MGMT = 143;

const int _SC_FIFO = 144;

const int _SC_PIPE = 145;

const int _SC_FILE_ATTRIBUTES = 146;

const int _SC_FILE_LOCKING = 147;

const int _SC_FILE_SYSTEM = 148;

const int _SC_MONOTONIC_CLOCK = 149;

const int _SC_MULTI_PROCESS = 150;

const int _SC_SINGLE_PROCESS = 151;

const int _SC_NETWORKING = 152;

const int _SC_READER_WRITER_LOCKS = 153;

const int _SC_SPIN_LOCKS = 154;

const int _SC_REGEXP = 155;

const int _SC_REGEX_VERSION = 156;

const int _SC_SHELL = 157;

const int _SC_SIGNALS = 158;

const int _SC_SPAWN = 159;

const int _SC_SPORADIC_SERVER = 160;

const int _SC_THREAD_SPORADIC_SERVER = 161;

const int _SC_SYSTEM_DATABASE = 162;

const int _SC_SYSTEM_DATABASE_R = 163;

const int _SC_TIMEOUTS = 164;

const int _SC_TYPED_MEMORY_OBJECTS = 165;

const int _SC_USER_GROUPS = 166;

const int _SC_USER_GROUPS_R = 167;

const int _SC_2_PBS = 168;

const int _SC_2_PBS_ACCOUNTING = 169;

const int _SC_2_PBS_LOCATE = 170;

const int _SC_2_PBS_MESSAGE = 171;

const int _SC_2_PBS_TRACK = 172;

const int _SC_SYMLOOP_MAX = 173;

const int _SC_STREAMS = 174;

const int _SC_2_PBS_CHECKPOINT = 175;

const int _SC_V6_ILP32_OFF32 = 176;

const int _SC_V6_ILP32_OFFBIG = 177;

const int _SC_V6_LP64_OFF64 = 178;

const int _SC_V6_LPBIG_OFFBIG = 179;

const int _SC_HOST_NAME_MAX = 180;

const int _SC_TRACE = 181;

const int _SC_TRACE_EVENT_FILTER = 182;

const int _SC_TRACE_INHERIT = 183;

const int _SC_TRACE_LOG = 184;

const int _SC_LEVEL1_ICACHE_SIZE = 185;

const int _SC_LEVEL1_ICACHE_ASSOC = 186;

const int _SC_LEVEL1_ICACHE_LINESIZE = 187;

const int _SC_LEVEL1_DCACHE_SIZE = 188;

const int _SC_LEVEL1_DCACHE_ASSOC = 189;

const int _SC_LEVEL1_DCACHE_LINESIZE = 190;

const int _SC_LEVEL2_CACHE_SIZE = 191;

const int _SC_LEVEL2_CACHE_ASSOC = 192;

const int _SC_LEVEL2_CACHE_LINESIZE = 193;

const int _SC_LEVEL3_CACHE_SIZE = 194;

const int _SC_LEVEL3_CACHE_ASSOC = 195;

const int _SC_LEVEL3_CACHE_LINESIZE = 196;

const int _SC_LEVEL4_CACHE_SIZE = 197;

const int _SC_LEVEL4_CACHE_ASSOC = 198;

const int _SC_LEVEL4_CACHE_LINESIZE = 199;

const int _SC_IPV6 = 235;

const int _SC_RAW_SOCKETS = 236;

const int _SC_V7_ILP32_OFF32 = 237;

const int _SC_V7_ILP32_OFFBIG = 238;

const int _SC_V7_LP64_OFF64 = 239;

const int _SC_V7_LPBIG_OFFBIG = 240;

const int _SC_SS_REPL_MAX = 241;

const int _SC_TRACE_EVENT_NAME_MAX = 242;

const int _SC_TRACE_NAME_MAX = 243;

const int _SC_TRACE_SYS_MAX = 244;

const int _SC_TRACE_USER_EVENT_MAX = 245;

const int _SC_XOPEN_STREAMS = 246;

const int _SC_THREAD_ROBUST_PRIO_INHERIT = 247;

const int _SC_THREAD_ROBUST_PRIO_PROTECT = 248;

const int _SC_MINSIGSTKSZ = 249;

const int _SC_SIGSTKSZ = 250;

const int _CS_PATH = 0;

const int _CS_V6_WIDTH_RESTRICTED_ENVS = 1;

const int _CS_POSIX_V6_WIDTH_RESTRICTED_ENVS = 1;

const int _CS_GNU_LIBC_VERSION = 2;

const int _CS_GNU_LIBPTHREAD_VERSION = 3;

const int _CS_V5_WIDTH_RESTRICTED_ENVS = 4;

const int _CS_POSIX_V5_WIDTH_RESTRICTED_ENVS = 4;

const int _CS_V7_WIDTH_RESTRICTED_ENVS = 5;

const int _CS_POSIX_V7_WIDTH_RESTRICTED_ENVS = 5;

const int _CS_LFS_CFLAGS = 1000;

const int _CS_LFS_LDFLAGS = 1001;

const int _CS_LFS_LIBS = 1002;

const int _CS_LFS_LINTFLAGS = 1003;

const int _CS_LFS64_CFLAGS = 1004;

const int _CS_LFS64_LDFLAGS = 1005;

const int _CS_LFS64_LIBS = 1006;

const int _CS_LFS64_LINTFLAGS = 1007;

const int _CS_XBS5_ILP32_OFF32_CFLAGS = 1100;

const int _CS_XBS5_ILP32_OFF32_LDFLAGS = 1101;

const int _CS_XBS5_ILP32_OFF32_LIBS = 1102;

const int _CS_XBS5_ILP32_OFF32_LINTFLAGS = 1103;

const int _CS_XBS5_ILP32_OFFBIG_CFLAGS = 1104;

const int _CS_XBS5_ILP32_OFFBIG_LDFLAGS = 1105;

const int _CS_XBS5_ILP32_OFFBIG_LIBS = 1106;

const int _CS_XBS5_ILP32_OFFBIG_LINTFLAGS = 1107;

const int _CS_XBS5_LP64_OFF64_CFLAGS = 1108;

const int _CS_XBS5_LP64_OFF64_LDFLAGS = 1109;

const int _CS_XBS5_LP64_OFF64_LIBS = 1110;

const int _CS_XBS5_LP64_OFF64_LINTFLAGS = 1111;

const int _CS_XBS5_LPBIG_OFFBIG_CFLAGS = 1112;

const int _CS_XBS5_LPBIG_OFFBIG_LDFLAGS = 1113;

const int _CS_XBS5_LPBIG_OFFBIG_LIBS = 1114;

const int _CS_XBS5_LPBIG_OFFBIG_LINTFLAGS = 1115;

const int _CS_POSIX_V6_ILP32_OFF32_CFLAGS = 1116;

const int _CS_POSIX_V6_ILP32_OFF32_LDFLAGS = 1117;

const int _CS_POSIX_V6_ILP32_OFF32_LIBS = 1118;

const int _CS_POSIX_V6_ILP32_OFF32_LINTFLAGS = 1119;

const int _CS_POSIX_V6_ILP32_OFFBIG_CFLAGS = 1120;

const int _CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS = 1121;

const int _CS_POSIX_V6_ILP32_OFFBIG_LIBS = 1122;

const int _CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS = 1123;

const int _CS_POSIX_V6_LP64_OFF64_CFLAGS = 1124;

const int _CS_POSIX_V6_LP64_OFF64_LDFLAGS = 1125;

const int _CS_POSIX_V6_LP64_OFF64_LIBS = 1126;

const int _CS_POSIX_V6_LP64_OFF64_LINTFLAGS = 1127;

const int _CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS = 1128;

const int _CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS = 1129;

const int _CS_POSIX_V6_LPBIG_OFFBIG_LIBS = 1130;

const int _CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS = 1131;

const int _CS_POSIX_V7_ILP32_OFF32_CFLAGS = 1132;

const int _CS_POSIX_V7_ILP32_OFF32_LDFLAGS = 1133;

const int _CS_POSIX_V7_ILP32_OFF32_LIBS = 1134;

const int _CS_POSIX_V7_ILP32_OFF32_LINTFLAGS = 1135;

const int _CS_POSIX_V7_ILP32_OFFBIG_CFLAGS = 1136;

const int _CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS = 1137;

const int _CS_POSIX_V7_ILP32_OFFBIG_LIBS = 1138;

const int _CS_POSIX_V7_ILP32_OFFBIG_LINTFLAGS = 1139;

const int _CS_POSIX_V7_LP64_OFF64_CFLAGS = 1140;

const int _CS_POSIX_V7_LP64_OFF64_LDFLAGS = 1141;

const int _CS_POSIX_V7_LP64_OFF64_LIBS = 1142;

const int _CS_POSIX_V7_LP64_OFF64_LINTFLAGS = 1143;

const int _CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS = 1144;

const int _CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS = 1145;

const int _CS_POSIX_V7_LPBIG_OFFBIG_LIBS = 1146;

const int _CS_POSIX_V7_LPBIG_OFFBIG_LINTFLAGS = 1147;

const int _CS_V6_ENV = 1148;

const int _CS_V7_ENV = 1149;

const int _GETOPT_POSIX_H = 1;

const int _GETOPT_CORE_H = 1;

const int F_ULOCK = 0;

const int F_LOCK = 1;

const int F_TLOCK = 2;

const int F_TEST = 3;

const int CLOSE_RANGE_UNSHARE = 2;

const int CLOSE_RANGE_CLOEXEC = 4;
